# Generated by Django 5.0.1 on 2024-04-26 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackjack", "0002_playerwins_gameroom_player"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blackjackgame",
            name="player",
        ),
        migrations.AddField(
            model_name="blackjackgame",
            name="players",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
